### ISSUE TITLE
Documentation clean-up

### ISSUE THREAD

**Issue by gromgull** [RDFLib/rdflib#265]
Some of our documentation is a bit out-dated and/or wrong. 
I'll try to collect stuff to clean up here. 

I think we have (or should have) three types of docs:
1. various "getting started" articles - how to parse, how to do SPO queries, how to do sparql, how to create your own RDF, how to serialize
2. In depth - literal<->python mapping, more stores, more SPARQL details, etc. 
3. Pure reference API docs - previously we did these with epydoc - but that project has died - I've nearly got it working with sphinx-apidoc locally, I'll commit some time soonishly.

For 3 doc-strings are of course crucial - but since sphinx makes it very easy to pull in bits of doc strings into other pages it is also useful for 2 and bit of it for 1. 
1. is partially there: 
   - https://github.com/RDFLib/rdflib/blob/master/docs/gettingstarted.rst
   - https://github.com/RDFLib/rdflib/blob/master/docs/intro_to_graphs.rst
   - https://github.com/RDFLib/rdflib/blob/master/docs/intro_to_sparql.rst
2. we have lots of bits of in depth docs - the challenge is more structuring and making sure it is still right :) 
3. I'll fix the technical part - everyone can write/update docstrings. 
## Todos
- [ ] Update docstrings to use http://sphinx-doc.org/domains.html?highlight=param#info-field-lists

These need updates: 
- [x] https://github.com/RDFLib/rdflib/blob/master/docs/plugin_serializers.rst
- [x] https://github.com/RDFLib/rdflib/blob/master/docs/plugin_parsers.rst
- [x] https://github.com/RDFLib/rdflib/blob/master/docs/persistence.rst

These I would convert to pure code examples in ./examples
- [x] https://github.com/RDFLib/rdflib/blob/master/docs/howto.rst
- [x] https://github.com/RDFLib/rdflib/blob/master/docs/assorted_examples.rst

This I would delete: 
- [x] https://github.com/RDFLib/rdflib/blob/master/docs/graphs_bnodes.rst 

Not sure about: 
- [ ] https://github.com/RDFLib/rdflib/blob/master/docs/univrdfstore.rst
- [ ] https://github.com/RDFLib/rdflib/blob/master/docs/persisting_n3_terms.rst
